{"name": "Добавление нового пользователя", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'tests/attachments/add_user.png'", "trace": "browser = <selenium.webdriver.support.event_firing_webdriver.EventFiringWebDriver object at 0x7f483d2b4520>\n\n    @allure.parent_suite(\"Проверка тестового магазина opencart\")\n    @allure.suite(\"Тесты главной страницы\")\n    @allure.epic(\"Проверка магазина на opencart\")\n    @allure.feature(\"Проверка главной страницы\")\n    @allure.title(\"Добавление нового пользователя\")\n    @allure.description(\"\"\"Тест проверяет возможность добавить нового пользователя\"\"\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_add_new_user(browser):\n        main_page = MainPage(browser).open()\n>       allure.attach.file(source='tests/attachments/add_user.png', attachment_type=allure.attachment_type.PNG)\n\n../../phyton_qa_docker/tests/test_main_page.py:43: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../venv/lib/python3.8/site-packages/allure_commons/_allure.py:182: in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\n../venv/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n../venv/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n../venv/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n../../phyton_qa_docker/venv/lib/python3.8/site-packages/allure_pytest/listener.py:226: in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\n../venv/lib/python3.8/site-packages/allure_commons/reporter.py:114: in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\n../venv/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n../venv/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n../venv/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n../venv/lib/python3.8/site-packages/allure_commons/logger.py:53: in report_attached_file\n    shutil.copy2(source, destination)\n/usr/lib/python3.8/shutil.py:435: in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nsrc = 'tests/attachments/add_user.png'\ndst = '/home/anton/PycharmProjects/python_qa_ci_jenkins/tests/allure-results/ca8dc311-af87-4e1c-a4e4-e6ab07ead107-attachment.png'\n\n    def copyfile(src, dst, *, follow_symlinks=True):\n        \"\"\"Copy data from src to dst in the most efficient way possible.\n    \n        If follow_symlinks is not set and src is a symbolic link, a new\n        symlink will be created instead of copying the file it points to.\n    \n        \"\"\"\n        sys.audit(\"shutil.copyfile\", src, dst)\n    \n        if _samefile(src, dst):\n            raise SameFileError(\"{!r} and {!r} are the same file\".format(src, dst))\n    \n        file_size = 0\n        for i, fn in enumerate([src, dst]):\n            try:\n                st = _stat(fn)\n            except OSError:\n                # File most likely does not exist\n                pass\n            else:\n                # XXX What about other special files? (sockets, devices...)\n                if stat.S_ISFIFO(st.st_mode):\n                    fn = fn.path if isinstance(fn, os.DirEntry) else fn\n                    raise SpecialFileError(\"`%s` is a named pipe\" % fn)\n                if _WINDOWS and i == 0:\n                    file_size = st.st_size\n    \n        if not follow_symlinks and _islink(src):\n            os.symlink(os.readlink(src), dst)\n        else:\n>           with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:\nE           FileNotFoundError: [Errno 2] No such file or directory: 'tests/attachments/add_user.png'\n\n/usr/lib/python3.8/shutil.py:264: FileNotFoundError"}, "description": "Тест проверяет возможность добавить нового пользователя", "attachments": [{"source": "ca8dc311-af87-4e1c-a4e4-e6ab07ead107-attachment.png", "type": "image/png"}, {"name": "log", "source": "3cc0f436-e503-4e0f-a0bb-a2c3e686ea67-attachment.txt", "type": "text/plain"}], "start": 1625933231259, "stop": 1625933233348, "uuid": "5808d63b-767a-4943-bee6-e2cdda79d757", "historyId": "4284e047d9212dfd146b0a0bd014e1ca", "testCaseId": "92f59944acfc6a69247e38652c137a39", "fullName": "tests.test_main_page#test_add_new_user", "labels": [{"name": "severity", "value": "critical"}, {"name": "suite", "value": "Тесты главной страницы"}, {"name": "parentSuite", "value": "Проверка тестового магазина opencart"}, {"name": "feature", "value": "Проверка главной страницы"}, {"name": "epic", "value": "Проверка магазина на opencart"}, {"name": "host", "value": "anton-Aspire-Z3-605"}, {"name": "thread", "value": "13102-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_main_page"}]}